spring:
  application:
    name: Interpark
  datasource:
    url: jdbc:mysql://localhost:13306/Interpark
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456789

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
  #  sql:
#    init:
#      mode: always

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379